### ISSUE TITLE
Excessive Data Use

### ISSUE THREAD

**Issue by whompy** [pirl/pirl#29]
#### System information

Pirl version: `1.0.1`
OS & Version: Linux (Arch Linux)
Commit hash : (if `develop`)

I suddenly saw a massive uptick in data use that is actually causing me to exceed my bandwidth limit since I started running a full node. Would you consider adding a bandwidth limit flag (sumokoin has a configurable option, for instance) to curb the issue? I like to support the network by running a full node, but will not be able to continue doing so presently.

**Comment by cetindogu** [comment]
bandwidth limiting will NOT prevent your exceeding. Just takes more time to complete. This is not an issue. Please just send dev team to a Suggestion e-mail. Have a nice day.

**Comment by masterdubs** [comment]
You should update to the new node. It solve the problem.
