### ISSUE TITLE
Compile warnings.

### ISSUE THREAD

**Issue by Serpent6877** [pirl/pirl#33]
PIRL: 1.8.1.1
OS: Ubuntu 17.10
GO: 1.9.4

github.com/pirl/pirl/internal/jsre
# github.com/pirl/pirl/vendor/gopkg.in/olebedev/go-duktape.v3
In file included from vendor/gopkg.in/olebedev/go-duktape.v3/api.go:7:0:
vendor/gopkg.in/olebedev/go-duktape.v3/api.go: In function '_duk_error':
vendor/gopkg.in/olebedev/go-duktape.v3/duktape.h:510:127: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  (duk_error_raw((ctx), (duk_errcode_t) (err_code), (const char *) (DUK_FILE_MACRO), (duk_int_t) (DUK_LINE_MACRO), __VA_ARGS__), (duk_ret_t) 0)
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
vendor/gopkg.in/olebedev/go-duktape.v3/api.go:153:2: note: in expansion of macro 'duk_error'
  duk_error(ctx, err_code, "%s", str);
  ^~~~~~~~~
github.com/pirl/pirl/crypto


Seem to get these warnings upon make. Can not tell if it effects the daemon.

**Comment by masterdubs** [comment]
fixed in hulk
