### ISSUE TITLE
getTransactionReceipt(string) is returning error when the tx receipt is submitted but not mined.

### ISSUE THREAD

**Issue by mvilera** [pirl/pirl#35]
Hi there, 

As title says, when we submit a transaction and try to get the receipt soon afterwards the method eth.getTransactionReceipt returns an exception (unknown transaction) instead of null, as soon as the tx is mined it will return the expected behavior.

This was fixed on geth 1.8.2 according to ethereum/go-ethereum#16217

**Comment by Serpent6877** [comment]
I see this has still not been fixed. Any update on if/when?

**Comment by masterdubs** [comment]
Please open issue in our gitlab https://git.pirl.io/community/pirl , we already updated the node.
